<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <!-- Win10 machines without CET refuse CETCOMPAT=ON apphosts. -->
    <CETCompat>false</CETCompat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InTheHand.Net.Bluetooth" Version="4.2.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlueType.Protocol\BlueType.Protocol.csproj" />
  </ItemGroup>

</Project>
